spring:
  datasource:
    url: jdbc:mysql://200.128.9.179:3306/bd_camiseta?createDatabaseIfNotExist=true
    username: remoto
    password: remoto
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
