server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://200.128.9.179:3306/bd_camiseta?createDatabaseIfNotExist=true
    username: remoto
    password: remoto
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true